server:
  port: 8888
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: mybatis-service
          uri: lb://mybatis-service
          order: 9000
          predicates:
            - Path=/operator/**