server:
  port: 80
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 192.168.3.3:8080
  servlet:
    multipart:
      max-file-size: 10MB
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 30000